### ISSUE TITLE
magni_description missing install rules

### ISSUE THREAD

**Issue by rohbotics** [UbiquityRobotics/magni_robot#175]
We need to add the cmake install rules for the default extrinsics, they are not present in the debian version of the package.

**Comment by JanezCim** [comment]
When making the current state I was planing that the default extrinsics would live in `magni_robot/magni_description/extrinsics/`. So im not sure what you mean with "add the cmake install rules for the default extrinsics"

**Comment by anfederman** [comment]
Except the Magni gazebo launch doesn't find the camera in noetic because
the extrinsics folder isn't found. On the beta, the extrinsics folder was
missing, or perhaps under a param folder?

**Comment by JanezCim** [comment]
@anfederman do you mean the 
`[Errno 2] No such file or directory: u'/home/janez/Documents/Projects/ubiquityrobotics/magni_ws/src/magni_robot/magni_description/param/camera_extrinsics_forward.yaml' 
`
problem? That is a simple directory problem that I have just fixed here: https://github.com/UbiquityRobotics/magni_robot/pull/176  can you try if it works? I assigned you as a reviewer.

**Comment by anfederman** [comment]
This is still an issue in that in magni_gazebo  it was still looking for the extrinsics file in param  which didn't exist in /opt/ros/noetic/magni_description.    I fixed it locally by "sudo cp -r extrinsics param"

**Comment by JanezCim** [comment]
hmm, that is strange because it works on my Ubuntu 20.04, ROS Noetic machine just fine: 
by running 

`roslaunch magni_gazebo fiducial_world.launch`

![vsdf](https://user-images.githubusercontent.com/8426792/132480188-094e89bf-0f90-4d7f-a62d-ef0fa012a84a.png)

What machine are you using? Can you recheck that you are checkout and pulled the branch `bugfix-gazebo-extrinsicsfolder`? What command are you using to run the gazebo?

**Comment by anfederman** [comment]
***@***.***:~/catkin_ws/src/magni_robot$ git branch
  bugfix-gazebo-extrinsicsfolder
* noetic-devel
***@***.***:~/catkin_ws/src/magni_robot$

 [fiducial_marker_spawn-16] process has finished cleanly
log file:
/home/dr1bot/.ros/log/9120ef1c-10c6-11ec-ad8a-1778231a9cf4/fiducial_marker_spawn-16*.log
[ INFO] [1631120616.895179499, 0.700000000]: Updating map with 0
observations. Map has 16 fiducials
[ INFO] [1631120617.555781574, 0.800000000]: Updating map with 0
observations. Map has 16


but I only see the bottom fiducial. I'll try on the ARM64 pi and see if
there is any difference. Also, on RVIZ,I don't see the robot model until I
change from odm to base_link.

**Comment by JanezCim** [comment]
> ***@***.***:~/catkin_ws/src/magni_robot$ git branch
>   bugfix-gazebo-extrinsicsfolder
> * noetic-devel

This seems to be indicating that you are on `noetic-devel` branch, You should be on `bugfix-gazebo-extrinsicsfolder` branch. Please do so with 

```
cd ~/catkin_ws/src/magni_robot/
git checkout bugfix-gazebo-extrinsicsfolder 
git pull
```

recompile and try again

**Comment by rohbotics** [comment]
Hey  @JanezCim  

The issue is that by default only "installed" components of the package will be included in a binary distribution, and currently we are not installing the extrinsics. They need to be installed just like the launch and the urdf directories here:  https://github.com/UbiquityRobotics/magni_robot/blob/noetic-devel/magni_description/CMakeLists.txt#L114

**Comment by JanezCim** [comment]
@rohbotics oh okay i think i see the problem, but then I suspect that @anfederman is experiencing a completely different set of problems.

I've included the install rules in #177 

@anfederman  i think this is a discussion that is a duplication of #174 anyway, so lets continue solving that there.

**Comment by anfederman** [comment]
On my laptop, I might be missing something. For instance I have Magni robot
and fiducials, but no Raspicam node. So even though there is an extrinsics,
something else is missing. Same thing might be true on the ARM64 RPi., But
Raspicam node is there. It might be missing some dependacy.

**Comment by anfederman** [comment]
BTW  the bugfix has eliminated the magni_gazebo fiducial world not
displaying fiducials issue, which occurred on some of my platforms.

**Comment by JanezCim** [comment]
@anfederman ok we can continue the discussion for fidducials issue on #174
